name: Sync to Mirror Repository

on:
  push:
    branches:
      - main # o la rama que quieras sincronizar

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Push to mirror
        uses: wei/git-sync@v1
        env:
          GIT_SYNC_TOKEN: ${{ secrets.TOKEN }}
          GIT_SYNC_DEST: https://github.com/AngelMascaro/PRDEPLOY1.git
