name: Ejemplo de flujo de trabajo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Push cambios
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Auto-commit"
          git push https://<TOKEN>@github.com/AngelMascaro/PRDEPLOY1.git HEAD:main
