name: Sync to Mirror Repository

on:
  push:
    branches:
      - main # o la rama que quieras sincronizar

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push to mirror
        uses: wei/git-sync@v1
        env:
          GIT_SYNC_TOKEN: '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'
          GIT_SYNC_DEST: 'AngelMascaro/PRDEPLOY1'
